n=input('Digite algo:')
print(type(n))
print('É alfanumerico?',n.isalnum())
print('É alfabetico?',n.isalpha())
print('Esta tudo em maiusculo?',n.istitle())
print('É digito?',n.isdigit())
print('São todos digitos?',n.isnumeric())
print('É um texto imprimivel?',n.isprintable())
print('esta tudo em minusculo?',n.isupper())
